# Generated by Django 6.0.3 on 2026-03-18 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.IntegerField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('post_code', models.CharField(blank=True, max_length=10, null=True)),
                ('avg_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('avg_col', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('uni_id', models.AutoField(primary_key=True, serialize=False)),
                ('uni_name', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, choices=[('public', 'public'), ('private', 'private')], max_length=20, null=True)),
                ('ranking_global', models.IntegerField(blank=True, null=True)),
                ('ranking_by_sub', models.JSONField(blank=True, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('long', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('website_url', models.TextField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.ForeignKey(db_column='city_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='devserver.city')),
            ],
            options={
                'db_table': 'university',
            },
        ),
    ]
