# Generated by Django 6.0.3 on 2026-03-24 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcaHighlight',
            fields=[
                ('aca_highlight_id', models.AutoField(primary_key=True, serialize=False)),
                ('aca_highlight_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'aca_highlights',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.IntegerField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=100)),
                ('avg_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('avg_col', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ingredient_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ingredient_name', models.CharField(max_length=100)),
                ('how_to_eat', models.TextField(blank=True, null=True)),
                ('has_pork', models.BooleanField(default=False)),
                ('has_beef', models.BooleanField(default=False)),
                ('has_chicken', models.BooleanField(default=False)),
                ('for_vegan', models.BooleanField(default=False)),
                ('for_vegetarian', models.BooleanField(default=False)),
                ('has_diary', models.BooleanField(default=False)),
                ('has_glutten', models.BooleanField(default=False)),
                ('has_nut', models.BooleanField(default=False)),
                ('has_shellfish', models.BooleanField(default=False)),
                ('has_seafood', models.BooleanField(default=False)),
                ('has_sugar', models.BooleanField(default=False)),
                ('has_salt', models.BooleanField(default=False)),
                ('has_high_protein', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ingredients',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('lang_id', models.AutoField(primary_key=True, serialize=False)),
                ('lang_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'languages',
            },
        ),
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('nation_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nation_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'nations',
            },
        ),
        migrations.CreateModel(
            name='RouteType',
            fields=[
                ('route_type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('route_type_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'route_types',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'subjects',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('dish_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dish_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('city', models.ForeignKey(blank=True, db_column='city_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='devserver.city')),
                ('ingredients', models.ManyToManyField(db_table='DishIngredient', to='devserver.ingredient')),
            ],
            options={
                'db_table': 'dishes',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('tag', models.CharField(blank=True, max_length=50, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('cycle_years', models.IntegerField(blank=True, null=True)),
                ('time_of_year', models.CharField(blank=True, max_length=100, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('long', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('event_url', models.TextField(blank=True, null=True)),
                ('city', models.ForeignKey(db_column='city_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='devserver.city')),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='Housing',
            fields=[
                ('hou_id', models.AutoField(primary_key=True, serialize=False)),
                ('housing_type', models.CharField(blank=True, max_length=50, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('long', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('kaltmiete', models.CharField(blank=True, max_length=50, null=True)),
                ('warmmiete', models.CharField(blank=True, max_length=50, null=True)),
                ('housing_url', models.TextField(blank=True, null=True)),
                ('city', models.ForeignKey(db_column='city_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='devserver.city')),
            ],
            options={
                'db_table': 'housing',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('place_id', models.IntegerField(primary_key=True, serialize=False)),
                ('place_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('icon', models.CharField(blank=True, max_length=10, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('long', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('place_url', models.TextField(blank=True, null=True)),
                ('city', models.ForeignKey(db_column='city_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='devserver.city')),
                ('dishes', models.ManyToManyField(blank=True, db_table='place_dishes', to='devserver.dish')),
            ],
            options={
                'db_table': 'places',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.IntegerField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=100)),
                ('nation', models.ForeignKey(db_column='nation_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='devserver.nation')),
            ],
            options={
                'db_table': 'states',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(db_column='state_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='devserver.state'),
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('station_name', models.CharField(max_length=255)),
                ('transport_type', models.CharField(blank=True, max_length=50, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('long', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('city', models.ForeignKey(db_column='city_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='devserver.city')),
            ],
            options={
                'db_table': 'stations',
            },
        ),
        migrations.CreateModel(
            name='StationRouteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_type', models.ForeignKey(db_column='route_type_id', on_delete=django.db.models.deletion.CASCADE, to='devserver.routetype')),
                ('station', models.ForeignKey(db_column='station_id', on_delete=django.db.models.deletion.CASCADE, to='devserver.station')),
            ],
            options={
                'db_table': 'station_route_types',
                'unique_together': {('station', 'route_type')},
            },
        ),
        migrations.AddField(
            model_name='station',
            name='route_types',
            field=models.ManyToManyField(through='devserver.StationRouteType', to='devserver.routetype'),
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('stop_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('long', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('station', models.ForeignKey(db_column='station_id', on_delete=django.db.models.deletion.CASCADE, to='devserver.station')),
            ],
            options={
                'db_table': 'stops',
            },
        ),
        migrations.CreateModel(
            name='UniHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aca_highlight', models.ForeignKey(db_column='aca_highlight_id', on_delete=django.db.models.deletion.CASCADE, to='devserver.acahighlight')),
            ],
            options={
                'db_table': 'uni_highlights',
            },
        ),
        migrations.CreateModel(
            name='UniLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(db_column='lang_id', on_delete=django.db.models.deletion.CASCADE, to='devserver.language')),
            ],
            options={
                'db_table': 'uni_languages',
            },
        ),
        migrations.CreateModel(
            name='UniSubjectRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('subject', models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.CASCADE, to='devserver.subject')),
            ],
            options={
                'db_table': 'uni_subject_ranks',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('uni_id', models.AutoField(primary_key=True, serialize=False)),
                ('uni_name', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('institution_type', models.CharField(blank=True, max_length=50, null=True)),
                ('ranking_global', models.IntegerField(blank=True, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('long', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('uni_url', models.TextField(blank=True, null=True)),
                ('city', models.ForeignKey(db_column='city_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='devserver.city')),
                ('highlights', models.ManyToManyField(through='devserver.UniHighlight', to='devserver.acahighlight')),
                ('languages', models.ManyToManyField(through='devserver.UniLanguage', to='devserver.language')),
                ('subjects', models.ManyToManyField(through='devserver.UniSubjectRank', to='devserver.subject')),
            ],
            options={
                'db_table': 'universities',
            },
        ),
        migrations.AddField(
            model_name='unisubjectrank',
            name='uni',
            field=models.ForeignKey(db_column='uni_id', on_delete=django.db.models.deletion.CASCADE, to='devserver.university'),
        ),
        migrations.AddField(
            model_name='unilanguage',
            name='uni',
            field=models.ForeignKey(db_column='uni_id', on_delete=django.db.models.deletion.CASCADE, to='devserver.university'),
        ),
        migrations.AddField(
            model_name='unihighlight',
            name='uni',
            field=models.ForeignKey(db_column='uni_id', on_delete=django.db.models.deletion.CASCADE, to='devserver.university'),
        ),
        migrations.CreateModel(
            name='DishIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.ForeignKey(db_column='dish_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='devserver.dish')),
                ('ingredient', models.ForeignKey(db_column='ingredient_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='devserver.ingredient')),
            ],
            options={
                'db_table': 'dish_ingredients',
                'unique_together': {('dish', 'ingredient')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='unisubjectrank',
            unique_together={('uni', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='unilanguage',
            unique_together={('uni', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='unihighlight',
            unique_together={('uni', 'aca_highlight')},
        ),
    ]
