# Generated by Django 6.0.3 on 2026-03-18 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devserver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('dish_id', models.AutoField(primary_key=True, serialize=False)),
                ('dish_name', models.CharField(max_length=255)),
                ('ingredients', models.JSONField(blank=True, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('price_avg', models.CharField(blank=True, max_length=50, null=True)),
                ('how_to_eat', models.TextField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('has_pork', models.BooleanField(default=False)),
                ('has_beef', models.BooleanField(default=False)),
                ('has_meat', models.BooleanField(default=False)),
                ('has_dairy', models.BooleanField(default=False)),
                ('has_seafood', models.BooleanField(default=False)),
                ('has_vegan', models.BooleanField(default=False)),
                ('has_vegetarian', models.BooleanField(default=False)),
                ('city', models.ForeignKey(blank=True, db_column='city_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='devserver.city')),
            ],
            options={
                'db_table': 'dishes',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('event_time', models.DateTimeField(blank=True, null=True)),
                ('is_annual', models.BooleanField(default=False)),
                ('time_of_year', models.CharField(blank=True, max_length=100, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('long', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('city', models.ForeignKey(db_column='city_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='devserver.city')),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='Housing',
            fields=[
                ('hou_id', models.AutoField(primary_key=True, serialize=False)),
                ('housing_type', models.CharField(blank=True, max_length=50, null=True)),
                ('district_name', models.CharField(blank=True, max_length=100, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('long', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('kaltmiete', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('proximity', models.JSONField(blank=True, null=True)),
                ('highlight', models.TextField(blank=True, null=True)),
                ('costs', models.JSONField(blank=True, null=True)),
                ('data_source', models.TextField(blank=True, null=True)),
                ('city', models.ForeignKey(db_column='city_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='devserver.city')),
            ],
            options={
                'db_table': 'housing',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('place_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('long', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('hours', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('city', models.ForeignKey(db_column='city_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='devserver.city')),
            ],
            options={
                'db_table': 'places',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('station_name', models.CharField(max_length=255)),
                ('transport_type', models.CharField(blank=True, max_length=50, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('long', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('lines', models.JSONField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.ForeignKey(db_column='city_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='devserver.city')),
            ],
            options={
                'db_table': 'stations',
            },
        ),
    ]
