# Generated by Django 6.0.3 on 2026-03-22 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devserver', '0002_dish_event_housing_place_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcaHighlight',
            fields=[
                ('aca_highlight_id', models.AutoField(primary_key=True, serialize=False)),
                ('aca_highlight_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'aca_highlights',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ingredient_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ingredient_name', models.CharField(max_length=100)),
                ('how_to_eat', models.TextField(blank=True, null=True)),
                ('has_pork', models.BooleanField(default=False)),
                ('has_beef', models.BooleanField(default=False)),
                ('has_chicken', models.BooleanField(default=False)),
                ('for_vegan', models.BooleanField(default=False)),
                ('for_vegetarian', models.BooleanField(default=False)),
                ('has_diary', models.BooleanField(default=False)),
                ('has_glutten', models.BooleanField(default=False)),
                ('has_nut', models.BooleanField(default=False)),
                ('has_shellfish', models.BooleanField(default=False)),
                ('has_seafood', models.BooleanField(default=False)),
                ('has_sugar', models.BooleanField(default=False)),
                ('has_salt', models.BooleanField(default=False)),
                ('has_high_protein', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ingredients',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('lang_id', models.AutoField(primary_key=True, serialize=False)),
                ('lang_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'languages',
            },
        ),
        migrations.CreateModel(
            name='RouteType',
            fields=[
                ('route_type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('route_type_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'route_types',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'subjects',
            },
        ),
        migrations.CreateModel(
            name='UniSubjectRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('subject', models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.CASCADE, to='devserver.subject')),
            ],
            options={
                'db_table': 'uni_subject_ranks',
            },
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
        migrations.RenameField(
            model_name='dish',
            old_name='how_to_eat',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='event_name',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_time',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='housing',
            old_name='data_source',
            new_name='housing_url',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='name',
            new_name='place_name',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='image',
            new_name='place_url',
        ),
        migrations.RenameField(
            model_name='university',
            old_name='language',
            new_name='institution_type',
        ),
        migrations.RenameField(
            model_name='university',
            old_name='website_url',
            new_name='uni_url',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='has_beef',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='has_dairy',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='has_meat',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='has_pork',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='has_seafood',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='has_vegan',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='has_vegetarian',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='image',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='price_avg',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_annual',
        ),
        migrations.RemoveField(
            model_name='event',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='housing',
            name='costs',
        ),
        migrations.RemoveField(
            model_name='housing',
            name='district_name',
        ),
        migrations.RemoveField(
            model_name='housing',
            name='highlight',
        ),
        migrations.RemoveField(
            model_name='housing',
            name='image',
        ),
        migrations.RemoveField(
            model_name='housing',
            name='proximity',
        ),
        migrations.RemoveField(
            model_name='place',
            name='address',
        ),
        migrations.RemoveField(
            model_name='place',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='place',
            name='price',
        ),
        migrations.RemoveField(
            model_name='place',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='place',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='place',
            name='website',
        ),
        migrations.RemoveField(
            model_name='station',
            name='description',
        ),
        migrations.RemoveField(
            model_name='station',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='station',
            name='image',
        ),
        migrations.RemoveField(
            model_name='station',
            name='lines',
        ),
        migrations.RemoveField(
            model_name='university',
            name='ranking_by_sub',
        ),
        migrations.AddField(
            model_name='dish',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='cycle_years',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='housing',
            name='warmmiete',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='dishes',
            field=models.ManyToManyField(blank=True, db_table='place_dishes', to='devserver.dish'),
        ),
        migrations.AddField(
            model_name='place',
            name='icon',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='dish_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='dish',
            name='ingredients',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='university',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='university',
            table='universities',
        ),
        migrations.AddField(
            model_name='university',
            name='highlights',
            field=models.ManyToManyField(db_table='uni_highlights', to='devserver.acahighlight'),
        ),
        migrations.AddField(
            model_name='university',
            name='languages',
            field=models.ManyToManyField(db_table='university_languages', to='devserver.language'),
        ),
        migrations.AddField(
            model_name='station',
            name='route_types',
            field=models.ManyToManyField(db_table='station_route_types', to='devserver.routetype'),
        ),
        migrations.AddField(
            model_name='unisubjectrank',
            name='uni',
            field=models.ForeignKey(db_column='uni_id', on_delete=django.db.models.deletion.CASCADE, to='devserver.university'),
        ),
        migrations.AddField(
            model_name='university',
            name='subjects',
            field=models.ManyToManyField(through='devserver.UniSubjectRank', to='devserver.subject'),
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(db_table='dish_ingredients', to='devserver.ingredient'),
        ),
        migrations.AlterUniqueTogether(
            name='unisubjectrank',
            unique_together={('uni', 'subject')},
        ),
    ]
