# Generated by Django 6.0.3 on 2026-03-22 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devserver', '0003_acahighlight_ingredient_language_routetype_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('nation_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nation_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'nation',
            },
        ),
        migrations.RemoveField(
            model_name='city',
            name='post_code',
        ),
        migrations.RemoveField(
            model_name='city',
            name='state',
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.IntegerField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=100)),
                ('nation', models.ForeignKey(db_column='nation_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='devserver.nation')),
            ],
            options={
                'db_table': 'state',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='state_id',
            field=models.ForeignKey(db_column='state_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='devserver.state'),
        ),
    ]
