import {
    Music, Theater, Trees, Star, Ticket, Calendar, Users, Sparkles, Film, Coffee, Moon, Sun
} from 'lucide-react';

export const VENUES = [
    {
        name: 'Alte Oper Frankfurt',
        type: 'Concert Hall & Opera',
        icon: <Music className="w-7 h-7" />,
        color: 'from-purple-600 to-indigo-600',
        bg: 'bg-purple-50',
        image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80',
        description: 'Frankfurt\'s iconic neo-Renaissance concert hall hosting world-class orchestras, opera, and classical performances.',
        address: 'Opernplatz 1, 60313 Frankfurt',
        hours: 'Box office: Mon–Fri 10:00–19:00',
        highlights: ['International orchestras', 'Opera productions', 'Jazz & pop concerts', 'New Year\'s gala'],
        price: '€15 – €120',
        website: 'https://www.alteoper.de',
    },
    {
        name: 'Städel Museum',
        type: 'Art Museum',
        icon: <Star className="w-7 h-7" />,
        color: 'from-amber-500 to-orange-500',
        bg: 'bg-amber-50',
        image: 'https://images.unsplash.com/photo-1541367777708-7905fe3296c0?auto=format&fit=crop&w=800&q=80',
        description: 'One of Germany\'s most significant art museums with works spanning 700 years, from the Middle Ages to the present day.',
        address: 'Schaumainkai 63, 60596 Frankfurt',
        hours: 'Tue–Sun 10:00–18:00 (Thu until 21:00)',
        highlights: ['700 years of art history', 'Botticelli to Picasso', 'Garden events', 'Student discounts'],
        price: '€16 (students €14)',
        website: 'https://www.staedelmuseum.de',
    },
    {
        name: 'Palmengarten',
        type: 'Botanical Garden & Events',
        icon: <Trees className="w-7 h-7" />,
        color: 'from-green-500 to-emerald-600',
        bg: 'bg-green-50',
        image: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?auto=format&fit=crop&w=800&q=80',
        description: 'A stunning 22-hectare botanical garden that transforms into an outdoor venue for summer concerts and festivals.',
        address: 'Siesmayerstraße 61, 60323 Frankfurt',
        hours: 'Daily 09:00–18:00 (seasonal variations)',
        highlights: ['Summer concerts', 'Greenhouse collections', 'Family events', 'Annual Rose Garden festival'],
        price: '€7 (students €3.50)',
        website: 'https://palmengarten.de',
    },
    {
        name: 'Berger Straße',
        type: 'Nightlife & Dining Strip',
        icon: <Moon className="w-7 h-7" />,
        color: 'from-rose-500 to-pink-600',
        bg: 'bg-rose-50',
        image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=800&q=80',
        description: 'Frankfurt\'s vibrant cultural mile with bars, restaurants, cafes, and independent shops. Popular with students.',
        address: 'Berger Straße, 60316 Frankfurt',
        hours: 'Bars open until 01:00–03:00',
        highlights: ['Student bars & pubs', 'International restaurants', 'Live music venues', 'Weekend markets'],
        price: 'Free entry (drinks from €3)',
        website: '#',
    },
    {
        name: 'Senckenberg Museum',
        type: 'Natural History Museum',
        icon: <Film className="w-7 h-7" />,
        color: 'from-teal-500 to-cyan-600',
        bg: 'bg-teal-50',
        image: 'https://images.unsplash.com/photo-1564419320461-6870880221ad?auto=format&fit=crop&w=800&q=80',
        description: 'Europe\'s second-largest natural history museum featuring massive dinosaur skeletons and biodiversity exhibitions.',
        address: 'Senckenberganlage 25, 60325 Frankfurt',
        hours: 'Mon–Sun 09:00–17:00 (Wed/Thu until 20:00)',
        highlights: ['Full dinosaur skeletons', 'Planet Earth showcase', 'Biodiversity Lab', 'Night museum events'],
        price: '€12 (students €6)',
        website: 'https://www.senckenberg.de',
    },
    {
        name: 'Kleinmarkthalle',
        type: 'Market & Local Food Hall',
        icon: <Coffee className="w-7 h-7" />,
        color: 'from-yellow-500 to-amber-600',
        bg: 'bg-yellow-50',
        image: 'https://images.unsplash.com/photo-1488459716781-31db52582fe9?auto=format&fit=crop&w=800&q=80',
        description: 'Frankfurt\'s beloved indoor market with 150+ stalls selling local produce, international foods, and street snacks.',
        address: 'Hasengasse 5-7, 60311 Frankfurt',
        hours: 'Mon–Fri 08:00–18:00, Sat 08:00–16:00',
        highlights: ['Fresh Frankfurt sausages', 'International spices', 'Local cheeses & wine', 'Upstairs wine bar'],
        price: 'Free entry',
        website: '#',
    },
];

export const EVENTS = [
    {
        name: 'Museumsuferfest',
        month: 'August',
        icon: <Sparkles className="w-5 h-5" />,
        color: 'text-purple-600',
        bg: 'bg-purple-100',
        description: 'Europe\'s largest culture festival along the museum riverbank. 3 days, 40+ museums, free entry.',
    },
    {
        name: 'Luminale',
        month: 'Spring (biennial)',
        icon: <Star className="w-5 h-5" />,
        color: 'text-yellow-600',
        bg: 'bg-yellow-100',
        description: 'Light art festival transforming Frankfurt\'s architecture into stunning illuminated art installations.',
    },
    {
        name: 'Weihnachtsmarkt',
        month: 'November – December',
        icon: <Theater className="w-5 h-5" />,
        color: 'text-red-600',
        bg: 'bg-red-100',
        description: 'One of Germany\'s oldest Christmas markets in the historic Römerberg. A magical student experience.',
    },
    {
        name: 'Mainfest',
        month: 'August',
        icon: <Sun className="w-5 h-5" />,
        color: 'text-amber-400',
        bg: 'bg-orange-100',
        description: 'A beloved folk festival along the Main riverbank with traditional foods, rides, and live entertainment.',
    },
    {
        name: 'Frankfurt Book Fair',
        month: 'October',
        icon: <Users className="w-5 h-5" />,
        color: 'text-blue-600',
        bg: 'bg-blue-100',
        description: 'The world\'s largest trade fair for books. Students can attend on public days for a unique cultural experience.',
    },
    {
        name: 'Dippemess',
        month: 'Spring & Autumn',
        icon: <Ticket className="w-5 h-5" />,
        color: 'text-green-600',
        bg: 'bg-green-100',
        description: 'Frankfurt\'s traditional funfair at the fairgrounds with rides, food stalls, and entertainment for all ages.',
    },
];

export const STATS = [
    { label: 'Venues & Clubs', value: '200+', icon: <Theater className="w-5 h-5" /> },
    { label: 'Annual Events', value: '50+', icon: <Calendar className="w-5 h-5" /> },
    { label: 'Museums', value: '30+', icon: <Star className="w-5 h-5" /> },
    { label: 'Free Entry Days', value: 'Weekly', icon: <Ticket className="w-5 h-5" /> },
];

export const ENTERTAINMENT_TIPS = [
    {
        tip: 'Museum Discount',
        icon: '🎟️',
        desc: 'Show your student ID for up to 50% off at most Frankfurt museums. Many offer free entry on certain days.',
    },
    {
        tip: 'Festivale Season',
        icon: '🎪',
        desc: 'Summer months (June-August) are packed with free open-air festivals along the Main River — perfect for students.',
    },
    {
        tip: 'NightRide Service',
        icon: '🚌',
        desc: 'RMV NightRide buses run every 30 minutes after midnight on weekends — great for getting home safe after events.',
    },
    {
        tip: 'Sachsenhausen District',
        icon: '🍺',
        desc: 'Frankfurt\'s pub quarter is famous for Apfelwein (apple wine) bars. Budget-friendly and uniquely German.',
    },
]